### PR TITLE
Collision layers selection

### LINKED ISSUE #6: Feature request: Allow selection of collision layers for recast
Currently, the wheels of the vehicle stick to the ground using raycasts. If the wheel drives over a collision layer that is not the ground (for example a standing capsule), the wheel will be pushed upwards.

I propose the ability to select the collision layer onto which raycasts will be valid.

### PR DESCRIPTION
**Pull request by arturkamieniecki**
I've added the ability to define collision layers for wheels, specifying which colliders should be used with wheel raycasts.

Resolves #6.

### CODE REVIEW

**Review by patrykantosz — COMMENTED** [review]
LGTM.

**Review by jhanca-robotecai — APPROVED** [review]
The code works as expected and the feature makes a lot of sense. However, I would prefer to keep this list in the `VehicleController` so the same setting does not have to be applied four times.

**Comment by arturkamieniecki** [comment]
I've moved the collision group selection to the vehicle dynamics controller instead of the wheels.

**Review by jhanca-robotecai — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
